"""speccify-core — shared spec loader, schema validator, resolver, codegen pipeline."""

from speccify_core.codegen import (
    SUPPORTED_TARGETS,
    CacheKey,
    CacheMissError,
    CodegenError,
    LlmClient,
    ReplayCache,
    ReplayCacheClient,
    TargetRender,
    render_for_target,
)
from speccify_core.loader import SpecLoader, SpecLoaderError
from speccify_core.lockfile import (
    CURRENT_LOCKFILE_SCHEMA_VERSION,
    DEFAULT_LOCKFILE_SCHEMA_PATH,
    DEFAULT_TEMPLATE_SET,
    DEFAULT_TEMPLATE_VERSION,
    LEGACY_V1_LOCKFILE_SCHEMA_PATH,
    AnyGeneratorPin,
    AnySignature,
    GeneratedFile,
    GeneratorPin,
    LlmGeneratorPin,
    LockEntry,
    Lockfile,
    LockfileError,
    NoneSignature,
    SigstoreSignature,
    TemplateGeneratorPin,
    build_lockfile,
)
from speccify_core.manifest import (
    DEFAULT_MANIFEST_SCHEMA_PATH,
    DEFAULT_REGISTRY_PATH,
    ManifestError,
    ProjectManifest,
)
from speccify_core.registry import (
    LocalRegistry,
    RegistryError,
    Spec,
    Version,
)
from speccify_core.resolver import (
    Range,
    RangeConflictError,
    Resolution,
    ResolvedGraph,
    Resolver,
    ResolverError,
    VersionNotFoundError,
)
from speccify_core.validator import (
    DEFAULT_SCHEMA_PATH,
    SchemaValidator,
    ValidationIssue,
)

__version__ = "0.0.0"

__all__ = [
    "CURRENT_LOCKFILE_SCHEMA_VERSION",
    "DEFAULT_LOCKFILE_SCHEMA_PATH",
    "DEFAULT_MANIFEST_SCHEMA_PATH",
    "DEFAULT_REGISTRY_PATH",
    "DEFAULT_SCHEMA_PATH",
    "DEFAULT_TEMPLATE_SET",
    "DEFAULT_TEMPLATE_VERSION",
    "LEGACY_V1_LOCKFILE_SCHEMA_PATH",
    "AnyGeneratorPin",
    "AnySignature",
    "NoneSignature",
    "SigstoreSignature",
    "CacheKey",
    "CacheMissError",
    "CodegenError",
    "GeneratedFile",
    "GeneratorPin",
    "LlmClient",
    "LlmGeneratorPin",
    "LocalRegistry",
    "LockEntry",
    "Lockfile",
    "LockfileError",
    "ManifestError",
    "ProjectManifest",
    "Range",
    "RangeConflictError",
    "RegistryError",
    "ReplayCache",
    "ReplayCacheClient",
    "Resolution",
    "SUPPORTED_TARGETS",
    "TargetRender",
    "ResolvedGraph",
    "Resolver",
    "ResolverError",
    "SchemaValidator",
    "Spec",
    "SpecLoader",
    "SpecLoaderError",
    "TemplateGeneratorPin",
    "ValidationIssue",
    "Version",
    "VersionNotFoundError",
    "__version__",
    "build_lockfile",
    "render_for_target",
]
