"""speccify-core — playbooks, sources, resolver and lockfile.

A playbook captures a complex, recurring workflow for coding agents: ordered
steps, the sources it was researched from, reusable assets, and the pitfalls you
would otherwise hit twice. This package parses playbooks, resolves them from
local or git sources, and pins them reproducibly.
"""

from speccify_core.check import (
    Finding,
    check_links,
    check_playbook,
    check_source_age,
)
from speccify_core.git_registry import (
    DEFAULT_GIT_CACHE_DIR,
    GitLibrary,
    GitLibraryError,
    GitRef,
    GitRegistry,
    GitRegistryError,
    GitRepoCache,
    is_git_ref,
    parse_git_ref,
)
from speccify_core.lockfile import (
    CURRENT_LOCKFILE_SCHEMA_VERSION,
    DEFAULT_LOCKFILE_SCHEMA_PATH,
    LockEntry,
    Lockfile,
    LockfileError,
    build_lockfile,
)
from speccify_core.manifest import (
    CURRENT_MANIFEST_SCHEMA_VERSION,
    DEFAULT_LIBRARY_PATH,
    DEFAULT_MANIFEST_SCHEMA_PATH,
    MANIFEST_FILENAME,
    ManifestError,
    ProjectManifest,
)
from speccify_core.playbook import (
    ASSET_DIR,
    DEFAULT_PLAYBOOK_SCHEMA_PATH,
    PLAYBOOK_FILENAME,
    STALE_SOURCE_DAYS,
    Acceptance,
    AppliesTo,
    Issue,
    Playbook,
    PlaybookError,
    Source,
    Step,
    parse_playbook,
    schema_issues,
    validate_playbook,
)
from speccify_core.registry import (
    Bundle,
    Library,
    LibraryError,
    LocalLibrary,
    LocalRegistry,
    MultiLibrary,
    MultiRegistry,
    Registry,
    RegistryError,
    Version,
    bundle_sha256,
    split_id,
)
from speccify_core.resolver import (
    Range,
    RangeConflictError,
    Resolution,
    ResolvedGraph,
    Resolver,
    ResolverError,
    VersionNotFoundError,
    parse_uses_entry,
)
from speccify_core.spec_index import (
    INDEX_ENTRY_DIR,
    INDEX_ENTRY_SCHEMA_PATH,
    IndexEntry,
    SpecIndexError,
    load_index,
    load_indexes,
    parse_index_entry,
    search_index,
)

__version__ = "0.0.0"

__all__ = [
    "ASSET_DIR",
    "Acceptance",
    "AppliesTo",
    "Bundle",
    "CURRENT_LOCKFILE_SCHEMA_VERSION",
    "CURRENT_MANIFEST_SCHEMA_VERSION",
    "DEFAULT_GIT_CACHE_DIR",
    "Finding",
    "check_links",
    "check_playbook",
    "check_source_age",
    "DEFAULT_LIBRARY_PATH",
    "DEFAULT_LOCKFILE_SCHEMA_PATH",
    "DEFAULT_MANIFEST_SCHEMA_PATH",
    "DEFAULT_PLAYBOOK_SCHEMA_PATH",
    "GitLibrary",
    "GitLibraryError",
    "GitRef",
    "GitRegistry",
    "GitRegistryError",
    "GitRepoCache",
    "INDEX_ENTRY_DIR",
    "INDEX_ENTRY_SCHEMA_PATH",
    "IndexEntry",
    "Issue",
    "Library",
    "LibraryError",
    "LocalLibrary",
    "LocalRegistry",
    "LockEntry",
    "Lockfile",
    "LockfileError",
    "MANIFEST_FILENAME",
    "ManifestError",
    "MultiLibrary",
    "MultiRegistry",
    "PLAYBOOK_FILENAME",
    "Playbook",
    "PlaybookError",
    "ProjectManifest",
    "Range",
    "RangeConflictError",
    "Registry",
    "RegistryError",
    "Resolution",
    "ResolvedGraph",
    "Resolver",
    "ResolverError",
    "STALE_SOURCE_DAYS",
    "Source",
    "SpecIndexError",
    "Step",
    "Version",
    "VersionNotFoundError",
    "__version__",
    "build_lockfile",
    "bundle_sha256",
    "is_git_ref",
    "load_index",
    "load_indexes",
    "parse_git_ref",
    "parse_index_entry",
    "parse_playbook",
    "parse_uses_entry",
    "schema_issues",
    "search_index",
    "split_id",
    "validate_playbook",
]
