import assert from "node:assert/strict";
import { chromium } from "playwright";
const base = process.env.SPECCIFY_MOCK_URL ?? "http://127.0.0.1:1421/dev/mock.html";
assert.ok(["localhost", "127.0.0.1"].includes(new URL(base).hostname));
const browser = await chromium.launch({ channel: "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1500, height: 940 } });
  page.setDefaultTimeout(10000);
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${base}?workspaces=1&workspace-shell=1`);
  const root = "/private/tmp/demo-workspace";
  const nav = page.getByRole("navigation", { name: "Workspace-Projekte" });
  const activate = async label => {
    const group = ({ Dateien: "Dateien", Git: "Dateien", Skills: "Orga", Playbooks: "Orga", Tools: "Technik", MCPs: "Technik", Agent: "Technik", Aktionen: "Technik", "Gemeinsames Board": "Specs" })[label];
    await nav.getByRole("tablist", { name: "Bereiche", exact: true }).getByRole("tab", { name: group, exact: true }).click();
    if (group !== "Specs") await nav.getByRole("tablist", { name: group, exact: true }).getByRole("tab", { name: label, exact: true }).click();
  };
  const terminal = id => page.getByRole("region", { name: `Terminal ${root}/${id}`, exact: true });
  const pane = id => page.locator(`[data-worktree-id="tree-${id}"]`);
  const area = id => page.getByRole("region", { name: `Arbeitsbereich ${root}/${id}`, exact: true });
  const inspector = id => page.getByRole("region", { name: `Inspektor ${root}/${id}`, exact: true });
  const calls = command => page.evaluate(command => window.__SPECCIFY_MOCK__.workspaceCalls.filter(call => call.command === command), command);
  const select = async (id, label) => { await pane(id).getByRole("button", { name: label, exact: true }).click(); };
  const cards = page.locator("[data-workspace-spec]");
  await cards.first().waitFor();
  assert.equal(await cards.count(), 4, "three repos plus linked feature worktree");
  assert.equal((await calls("terminal_open")).length, 0, "opening a workspace starts no terminals");
  await pane("api").getByRole("button", { name: "+ Spec in API", exact: true }).click();
  await page.getByRole("button", { name: "Abbrechen", exact: true }).click();
  await activate("Dateien");
  await activate("Gemeinsames Board");
  assert.equal(await page.getByRole("button", { name: "Abbrechen", exact: true }).count(), 0, "dismissed creation stays dismissed across tabs");
  await page.getByLabel("Specs tree-feature", { exact: true }).getByRole("button").click();
  await inspector("api-search").getByRole("tab", { name: /Tasks/ }).click();
  await inspector("api-search").getByRole("checkbox", { name: /Review/ }).check();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.workspaceCalls.some(call => call.command === "project_spec_toggle_task"));
  assert.equal((await calls("project_spec_toggle_task")).at(-1).args.project, `${root}/api-search`);
  await cards.filter({ hasText: "api-search" }).getByText(/2\/2 Aufgaben/).waitFor();
  await activate("Dateien");
  await pane("api").getByRole("button", { name: "shared.txt", exact: true }).click();
  await area("api").getByText(`Only ${root}/api`, { exact: true }).waitFor();
  const editor = area("api").locator(".cm-content");
  await editor.fill("API draft stays here\n");
  await pane("web").getByRole("button", { name: "shared.txt", exact: true }).click();
  await area("web").getByText(`Only ${root}/web`, { exact: true }).waitFor();
  await select("api", "API · api api");
  assert.match(await editor.innerText(), /API draft stays here/);
  await editor.press("Meta+s");
  assert.equal((await calls("project_write_file")).at(-1).args.project, `${root}/api`);
  await activate("Git");
  const message = area("api").getByLabel("Commit-Betreff", { exact: true });
  await message.fill("API commit draft");
  await select("web", "Web web");
  await area("web").getByLabel("Commit-Betreff", { exact: true }).fill("Web commit draft");
  await select("api", "API · api api");
  assert.equal(await message.inputValue(), "API commit draft");
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("speccify:git", { detail: "fetch" })));
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.workspaceCalls.some(call => call.command === "project_action_run"));
  assert.equal((await calls("project_action_run")).length, 1);
  assert.equal((await calls("project_action_run"))[0].args.project, `${root}/api`);
  // Terminal remains docked below the content.
  await terminal("api").getByRole("button", { name: "Agent-Terminal starten", exact: true }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.workspaceCalls.filter(call => call.command === "terminal_open").length === 1);
  await select("web", "Web web");
  await terminal("web").getByRole("button", { name: "Agent-Terminal starten", exact: true }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.workspaceCalls.filter(call => call.command === "terminal_open").length === 2);
  assert.deepEqual((await calls("terminal_open")).map(call => call.args.cwd).sort(), [`${root}/api`, `${root}/web`]);
  const count = (await calls("terminal_write")).length;
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("speccify:type-command", { detail: "only-web" })));
  assert.equal((await calls("terminal_write")).length, count + 1, "only active terminal receives text");
  const webTerminal = (await calls("terminal_open")).find(call => call.args.cwd.endsWith("/web")).args.id;
  assert.equal((await calls("terminal_write")).at(-1).args.id, webTerminal);
  const killedBeforeSwitch = (await calls("terminal_kill")).length;
  await activate("Skills");
  assert.equal((await calls("terminal_kill")).length, killedBeforeSwitch, "switching retains both processes");
  const liveIds = new Set((await calls("terminal_open")).map(call => call.args.id));
  assert.equal(liveIds.size, 2);
  assert.ok((await calls("terminal_kill")).every(call => !liveIds.has(call.args.id)), "Strict Mode cleanup cannot kill a live terminal");
  for (const label of ["Playbooks", "Tools", "MCPs", "Agent", "Aktionen"]) {
    await activate(label);
    await area("web").waitFor();
  }
  const beforeGroupingKills = (await calls("terminal_kill")).length;
  await page.evaluate(() => {
    const workspaces = JSON.parse(localStorage.getItem("speccify.test.workspaces"));
    workspaces[0].projects = [{ id: "suite", name: "Product Suite", repository_ids: ["repo-api", "repo-web", "repo-infra"] }];
    workspaces[0].revision++;
    localStorage.setItem("speccify.test.workspaces", JSON.stringify(workspaces));
  });
  await page.getByRole("button", { name: "Aktualisieren", exact: true }).click();
  await page.getByRole("region", { name: "Projektgruppe Product Suite" }).waitFor();
  assert.equal((await calls("terminal_kill")).length, beforeGroupingKills, "regrouping preserves mounted processes");
  await activate("Git");
  assert.equal(await area("web").getByLabel("Commit-Betreff", { exact: true }).inputValue(), "Web commit draft");
  await activate("Gemeinsames Board");
  await page.screenshot({ path: "/private/tmp/speccify-026-workspace.png", fullPage: true });
  for (const theme of ["light", "dark"]) {
    await page.evaluate(theme => document.documentElement.setAttribute("data-theme", theme), theme);
    await page.setViewportSize({ width: 1000, height: 700 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${theme}: no viewport overflow`);
  }
  await page.evaluate(() => { window.__SPECCIFY_MOCK__.missingTarget = "tree-web"; });
  await page.getByRole("button", { name: "Aktualisieren", exact: true }).click();
  await pane("web").getByText(/Worktree nicht verfügbar/).waitFor();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("speccify:type-command", { detail: "must-not-reach-missing-target" })));
  assert.equal((await calls("terminal_write")).length, count + 1);
  assert.deepEqual(await page.evaluate(() => window.__SPECCIFY_MOCK__.workspaceOpened), [], "no single-project windows opened");
  assert.deepEqual(errors, []);
  console.log("PASS workspace shell: grouped roots, shared editable board, exact file/Git/terminal targets, drafts and processes retained, missing target inhibited, narrow themes");
} finally { await browser.close(); }
