import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const url='http://127.0.0.1:1422/dev/mock.html?agentsettingstest=1';
const server=spawn(process.execPath,[fileURLToPath(new URL('../apps/desktop/node_modules/vite/bin/vite.js',import.meta.url)),'--host','127.0.0.1','--port','1422','--strictPort'],{cwd:fileURLToPath(new URL('../apps/desktop',import.meta.url)),stdio:'ignore'});
let browser;
try {
  for(let i=0;i<100;i++) { if(server.exitCode!==null) throw Error('Test server exited'); try {if((await fetch(url)).ok) break;} catch {} await new Promise(r=>setTimeout(r,100)); }
  browser=await chromium.launch({channel:process.env.SPECCIFY_TEST_BROWSER??'chrome'});
  const page=await browser.newPage({viewport:{width:1200,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  const search=page.getByLabel('Agent-Einstellungen suchen');
  await search.waitFor();
  const writes=()=>page.evaluate(()=>window.__AGENT_SETTINGS_TEST__.writes.length);
  assert.equal(await page.getByLabel('approval_policy',{exact:true}).inputValue(),'"on-request"');
  await page.getByText('Empfohlener Ausgangspunkt: Selbstständig arbeiten',{exact:true}).click();
  await page.getByRole('button',{name:'Profil in Entwurf übernehmen'}).click();
  assert.equal(await writes(),0,'Preset must be a draft');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.getByRole('status').waitFor();
  assert.equal(await writes(),1);
  const codex=await page.evaluate(()=>window.__AGENT_SETTINGS_TEST__.files['codex-config']);
  assert.match(codex,/auto_review/); assert.match(codex,/custom_key = "keep"/); assert.match(codex,/mcp_servers.demo/);
  await search.fill('windows.sandbox');
  await page.getByLabel('windows.sandbox',{exact:true}).waitFor();
  assert.match(await page.locator('body').innerText(),/einmalige Einrichtung/);
  await page.getByRole('button',{name:'Quelltext',exact:true}).click();
  await page.getByLabel('Agent-Konfiguration Quelltext').fill('[broken');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.waitForTimeout(100);
  assert.equal(await writes(),1,'Invalid config must not save');
  await page.getByRole('button',{name:'Änderungen zurücknehmen'}).click();
  await page.getByRole('button',{name:'Strukturierte Ansicht'}).click();
  await search.fill('approval_policy');
  await page.getByLabel('approval_policy',{exact:true}).selectOption('"never"');
  await page.evaluate(()=>window.__AGENT_SETTINGS_TEST__.files['codex-config']+='\n# external edit\n');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.getByText(/Die Datei wurde außerhalb dieses Editors geändert\./).waitFor();
  assert.equal(await writes(),1);
  await page.getByRole('button',{name:'Claude · Einstellungen',exact:true}).click();
  await page.getByText('Ungespeicherte Änderungen verwerfen?',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Weiter bearbeiten'}).click();
  assert.equal(await page.getByLabel('approval_policy',{exact:true}).inputValue(),'"never"');
  await page.getByRole('button',{name:'Claude · Einstellungen',exact:true}).click();
  await page.getByRole('button',{name:'Verwerfen und wechseln'}).click();
  await page.getByLabel('permissions.defaultMode',{exact:true}).waitFor();
  await page.getByLabel('permissions.defaultMode',{exact:true}).selectOption('"auto"');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.getByRole('status').waitFor();
  const claude=await page.evaluate(()=>JSON.parse(window.__AGENT_SETTINGS_TEST__.files['claude-settings']));
  assert.equal(claude.permissions.defaultMode,'auto'); assert.deepEqual(claude.permissions.allow,['Bash(npm test)']); assert.equal(claude.unknown.keep,7);
  await search.fill('permissions.allow');
  await page.getByLabel('permissions.allow',{exact:true}).fill('invalid-json');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.getByText('Error: permissions.allow: ungültiger JSON-Wert',{exact:true}).waitFor();
  assert.equal(await writes(),2);
  await page.screenshot({path:'/private/tmp/speccify-agent-settings.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS agent settings: search/help, preset draft, save, unknown preservation, syntax rejection, stale-editor conflict, dirty switch, Claude permissions, invalid complex field');
} finally { await browser?.close(); server.kill(); }
