import assert from "node:assert/strict";
import { chromium } from "playwright";
const base = process.env.SPECCIFY_MOCK_URL ?? "http://127.0.0.1:1421/dev/mock.html";
assert.ok(["localhost", "127.0.0.1"].includes(new URL(base).hostname));
const browser = await chromium.launch({ channel: "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1500, height: 940 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${base}?playbook-drafts=1`);
  await page.getByRole("tab", { name: "Orga", exact: true }).click();
  await page.getByRole("tab", { name: "Playbooks", exact: true }).click();
  const select = title => page.getByRole("button", { name: new RegExp(`^${title}`) }).click();
  await select("Research");
  await page.getByRole("status").filter({ hasText: "Draft — unverbindlicher Entwurf" }).waitFor();
  const research = ".agent/playbooks/research.md";
  await page.getByRole("button", { name: "Auftrag…", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Auftrag" });
  await dialog.getByLabel("Auftragstext").getAttribute("value");
  await page.waitForFunction(() => document.querySelector('[aria-label="Auftragstext"]')?.value.includes("status: draft"));
  assert.equal(await dialog.getByRole("button", { name: "Lesen und anwenden", exact: true }).count(), 0);
  assert.match(await dialog.getByLabel("Auftragstext").inputValue(), /keine Umsetzung oder Aktivierung/);
  await dialog.getByLabel("Auftragstext").fill("Discuss these ideas.");
  await dialog.getByRole("button", { name: "Kopieren", exact: true }).click();
  assert.match(await page.evaluate(() => window.__SPECCIFY_MOCK__.copiedPlaybook), /^Draft — unverbindlicher Entwurf/);
  await dialog.getByRole("button", { name: "Terminal starten", exact: true }).click();
  await page.waitForFunction(() => window.__speccifyQa.terminalReady());
  await dialog.getByRole("button", { name: "Ins Terminal einfügen", exact: true }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.terminalWrites.length > 0);
  assert.match(await page.evaluate(() => window.__SPECCIFY_MOCK__.terminalWrites.at(-1).data), /Draft — unverbindlicher Entwurf/);
  await dialog.getByRole("button", { name: "Schließen", exact: true }).click();
  await page.getByRole("button", { name: "Bearbeiten", exact: true }).click();
  const editor = page.getByLabel("Playbook-Inhalt", { exact: true });
  await editor.fill("# Research\n\nUpdated ideas.\n");
  await page.getByRole("button", { name: "Fertig", exact: true }).click();
  await page.waitForFunction(file => window.__SPECCIFY_MOCK__.playbookFiles[file].includes("Updated ideas"), research);
  let content = await page.evaluate(file => window.__SPECCIFY_MOCK__.playbookFiles[file], research);
  assert.match(content, /status: draft/); assert.match(content, /custom: keep-me/);
  await page.getByRole("button", { name: "Aktivieren", exact: true }).click();
  await page.waitForFunction(file => window.__SPECCIFY_MOCK__.playbookFiles[file].includes("status: active"), research);
  await page.getByRole("button", { name: "Auftrag…", exact: true }).click();
  await dialog.getByRole("button", { name: "Lesen und anwenden", exact: true }).waitFor();
  // A status change after preview must also affect the actual delivered copy.
  await page.evaluate(file => { window.__SPECCIFY_MOCK__.playbookFiles[file] = window.__SPECCIFY_MOCK__.playbookFiles[file].replace("status: active", "status: draft"); }, research);
  await dialog.getByRole("button", { name: "Kopieren", exact: true }).click();
  assert.match(await page.evaluate(() => window.__SPECCIFY_MOCK__.copiedPlaybook), /^Draft — unverbindlicher Entwurf/);
  await dialog.getByRole("button", { name: "Schließen", exact: true }).click();
  await select("Unknown status");
  await page.getByRole("status").filter({ hasText: "Unbekannter oder ungültiger" }).waitFor();
  await page.getByRole("button", { name: "Auftrag…", exact: true }).click();
  assert.equal(await dialog.getByRole("button", { name: "Lesen und anwenden", exact: true }).count(), 0);
  await dialog.getByRole("button", { name: "Schließen", exact: true }).click();
  await page.getByRole("button", { name: "+ Playbook", exact: true }).click();
  await page.getByLabel("Neues Playbook: Status").selectOption("draft");
  await page.getByPlaceholder("Name, z. B. Release").fill("New ideas");
  await page.getByPlaceholder("Name, z. B. Release").press("Enter");
  await page.getByText("Playbook-Status: Draft", { exact: false }).waitFor();
  await page.getByLabel("Playbook-Inhalt", { exact: true }).fill("# New ideas\n\nA new idea.\n");
  await page.getByRole("button", { name: "Fertig", exact: true }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.playbookFiles['.agent/playbooks/new-ideas.md']?.includes('A new idea.'));
  assert.match(await page.evaluate(() => window.__SPECCIFY_MOCK__.playbookFiles['.agent/playbooks/new-ideas.md']), /status: draft/);
  await page.getByLabel("Playbooks nach Status filtern").selectOption("draft");
  assert.equal(await page.getByRole("button", { name: /^Legacy procedure/ }).count(), 0);
  await page.reload();
  await page.getByRole("tab", { name: "Orga", exact: true }).click();
  await page.getByRole("tab", { name: "Playbooks", exact: true }).click();
  await select("New ideas");
  await page.getByRole("status").filter({ hasText: "Draft — unverbindlicher Entwurf" }).waitFor();
  await page.getByRole("button", { name: "Bearbeiten", exact: true }).click();
  await page.getByLabel("Playbook-Inhalt", { exact: true }).fill("# New ideas\n\nUnsaved conflicting idea.\n");
  await page.evaluate(() => { window.__SPECCIFY_MOCK__.playbookFiles['.agent/playbooks/new-ideas.md'] = '---\nstatus: active\n---\n# Externally activated\n'; });
  await page.getByRole("button", { name: "Fertig", exact: true }).click();
  await page.getByText(/Datei wurde zwischenzeitlich geändert/).waitFor();
  assert.match(await page.getByLabel("Playbook-Inhalt", { exact: true }).inputValue(), /Unsaved conflicting idea/);
  assert.match(await page.evaluate(() => window.__SPECCIFY_MOCK__.playbookFiles['.agent/playbooks/new-ideas.md']), /status: active/);
  // Both editor paths share the flat frontmatter contract, including CRLF and duplicates.
  assert.deepEqual(await page.evaluate(async () => {
    const { playbookStatus } = await import('/src/lib/playbooks.ts');
    return ['# Legacy', '---\nstatus: active\n---\n', "---\r\nstatus: 'draft' # ideas\r\n---\r\n", '---\nstatus: draft\nstatus: active\n---\n', '---\nstatus: draft', '\uFEFF---\nstatus: draft\n---\n'].map(playbookStatus);
  }), ['active','active','draft','invalid','invalid','draft']);
  assert.deepEqual(errors, []);
  console.log("PASS playbook drafts: create, CRLF metadata, explicit activation, status filter, safe fresh handover, invalid status and reload");
} finally { await browser.close(); }
