import assert from "node:assert/strict";
import { chromium } from "playwright";
const base = process.env.SPECCIFY_MOCK_URL ?? "http://127.0.0.1:1421/dev/mock.html";
assert.ok(["localhost", "127.0.0.1"].includes(new URL(base).hostname));
const browser = await chromium.launch({ channel: "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1500, height: 940 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${base}?workspaces=1&workspace-shell=1&workspace-knowledge=1`);
  await page.getByRole("button", { name: "Aktualisieren", exact: true }).waitFor();
  const tab = async name => { await page.evaluate(name => window.dispatchEvent(new CustomEvent("speccify:show-tab", { detail: name })), name); };
  const list = name => page.getByRole("region", { name: `Gemeinsame ${name}`, exact: true });
  const select = async (name, source) => list(name).locator("[data-knowledge-key]").filter({ hasText: new RegExp(`^.*${source} ·`) }).first().click();
  await tab("skills");
  await page.waitForFunction(() => document.querySelectorAll('[data-knowledge-key]').length === 3);
  assert.equal(await list("Skills").locator("[data-knowledge-key]").count(), 3);
  await select("Skills", "api");
  const apiArea = page.getByRole("region", { name: "Arbeitsbereich /private/tmp/demo-workspace/api", exact: true });
  await apiArea.getByText("Read only /private/tmp/demo-workspace/api.", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Auftrag…", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Auftrag" });
  await page.waitForFunction(() => document.querySelector('[aria-label="Auftragstext"]')?.value.includes('/api/.agent/skills/review/SKILL.md'));
  assert.match(await dialog.getByLabel("Auftragstext").inputValue(), /Ausführungs-cwd: \/private\/tmp\/demo-workspace\/api/);
  await dialog.getByRole("button", { name: "Schließen", exact: true }).click();
  await list("Skills").getByLabel("Wissensquelle filtern").selectOption("tree-web");
  assert.equal(await list("Skills").locator("[data-knowledge-key]").count(), 1);
  // Filtering changes the list, never the existing action's source.
  await apiArea.getByText("Read only /private/tmp/demo-workspace/api.", { exact: true }).waitFor();
  await select("Skills", "web");
  await list("Skills").getByLabel("Wissensziel wählen").selectOption("tree-api");
  await list("Skills").getByRole("button", { name: "Quellen durchsuchen / importieren" }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.workspaceCalls.some(call => call.command === "sources_list" && call.args.project?.endsWith("/api")));
  await tab("tools");
  await select("Tools", "web");
  await page.getByRole("region", { name: "Arbeitsbereich /private/tmp/demo-workspace/web", exact: true }).getByText("Run with cwd /private/tmp/demo-workspace/web.", { exact: true }).waitFor();
  await tab("mcps");
  await page.waitForFunction(() => document.querySelectorAll('[data-knowledge-key]').length === 6);
  assert.equal(await list("MCPs").locator("[data-knowledge-key]").count(), 6);
  assert.doesNotMatch(await list("MCPs").innerText(), /never-in-catalog/);
  await select("MCPs", "api");
  await list("MCPs").getByText(/im Root-Host noch nicht bestätigt/).waitFor();
  await tab("playbooks");
  await select("Playbooks", "api");
  await page.getByRole("button", { name: "Bearbeiten", exact: true }).click();
  const editor = apiArea.getByLabel("Playbook-Inhalt", { exact: true });
  await editor.fill("# Ideas\n\nAPI draft retained.\n");
  await select("Playbooks", "web");
  await list("Playbooks").getByRole("button", { name: "Liste aktualisieren" }).click();
  await select("Playbooks", "api");
  assert.match(await editor.inputValue(), /API draft retained/);
  await page.getByRole("button", { name: "Fertig", exact: true }).click();
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.knowledgeFiles.get('/private/tmp/demo-workspace/api/.agent/playbooks/ideas.md').includes('API draft retained'));
  const state = await page.evaluate(() => Object.fromEntries(window.__SPECCIFY_MOCK__.knowledgeFiles));
  assert.match(state['/private/tmp/demo-workspace/web/.agent/playbooks/ideas.md'], /Ideas from/);
  assert.match(state['/private/tmp/demo-workspace/api/.agent/playbooks/ideas.md'], /status: draft/);
  await list("Playbooks").getByLabel("Wissensziel wählen").selectOption("tree-web");
  await list("Playbooks").getByRole("button", { name: "Playbook hier anlegen" }).click();
  await page.getByLabel("Neues Playbook: Status").selectOption("draft");
  await page.getByPlaceholder("Name, z. B. Release").fill("New ideas");
  await page.getByPlaceholder("Name, z. B. Release").press("Enter");
  await page.waitForFunction(() => window.__SPECCIFY_MOCK__.knowledgeFiles.has('/private/tmp/demo-workspace/web/.agent/playbooks/new-ideas.md'));
  await page.evaluate(() => { window.__SPECCIFY_MOCK__.knowledgeOffline = "tree-web"; });
  await list("Playbooks").getByRole("button", { name: "Liste aktualisieren" }).click();
  await list("Playbooks").getByText(/web: Quelle nicht verfügbar/).waitFor();
  assert.equal(await page.getByRole("region", { name: "Arbeitsbereich /private/tmp/demo-workspace/web", exact: true }).getAttribute("inert"), "");
  await list("Playbooks").getByLabel("Wissensquelle filtern").selectOption(`root:workspace-demo`);
  await page.reload();
  await page.getByRole("button", { name: "Aktualisieren", exact: true }).waitFor();
  await tab("playbooks");
  await page.waitForFunction(() => document.querySelector('[aria-label="Wissensquelle filtern"]')?.querySelectorAll('option').length > 1);
  assert.equal(await list("Playbooks").getByLabel("Wissensquelle filtern").inputValue(), "root:workspace-demo");
  await select("Playbooks", "Root");
  await page.getByRole("region", { name: "Arbeitsbereich /private/tmp/demo-workspace", exact: true }).getByText("Ideas from /private/tmp/demo-workspace.", { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS common knowledge lists: root/children, duplicate names, source filters, scoped handover/import/create, retained drafts, unavailable source guards, reopen");
} finally { await browser.close(); }
