import assert from "node:assert/strict";
import { chromium } from "playwright";
const base = process.env.SPECCIFY_MOCK_URL ?? "http://127.0.0.1:1421/dev/mock.html";
assert.ok(["localhost", "127.0.0.1"].includes(new URL(base).hostname));
const browser = await chromium.launch({ channel: "chrome" });
try {
  const context = await browser.newContext({ viewport: { width: 1500, height: 1000 } });
  const dashboard = await context.newPage();
  const errors = [];
  dashboard.on("pageerror", error => errors.push(error.message));
  await dashboard.goto(`${base}?dashboard=1&workspaces=1`);
  await dashboard.getByRole("button", { name: "Settings", exact: true }).click();
  const depth = dashboard.getByLabel("Projekt-Erkennungstiefe", { exact: true });
  assert.equal(await depth.inputValue(), "1");
  await depth.selectOption("3");
  await dashboard.getByRole("button", { name: "Speichern", exact: true }).click();
  await dashboard.getByText("Gespeichert.", { exact: true }).waitFor();
  await dashboard.reload();
  await dashboard.getByRole("button", { name: "Settings", exact: true }).click();
  assert.equal(await depth.inputValue(), "3");
  const shell = await context.newPage();
  shell.on("pageerror", error => errors.push(error.message));
  await shell.goto(`${base}?workspaces=1&workspace-shell=1`);
  await shell.locator('[data-worktree-id="tree-web"]').waitFor();
  await shell.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem("speccify.test.workspaces"));
    saved[0].repositories.find(repo => repo.id === "repo-web").worktrees[0].path = `${saved[0].root}/api/external/web`;
    saved[0].repositories.find(repo => repo.id === "repo-web").worktrees[0].relative_path = "api/external/web";
    localStorage.setItem("speccify.test.workspaces", JSON.stringify(saved));
  });
  await shell.reload();
  const nav = shell.getByRole("navigation", { name: "Workspace-Projekte" });
  await nav.getByRole("tab", { name: "Dateien", exact: true }).click();
  await nav.getByRole("tab", { name: "Git", exact: true }).click();
  await shell.locator('[data-worktree-id="tree-web"]').getByRole("button", { name: "Web api/external/web", exact: true }).click();
  const draft = shell.getByRole("region", { name: "Arbeitsbereich /private/tmp/demo-workspace/api/external/web", exact: true, includeHidden: true }).getByLabel("Commit-Betreff", { exact: true });
  await draft.fill("Retained nested draft");
  await depth.selectOption("1");
  await dashboard.getByRole("button", { name: "Speichern", exact: true }).click();
  await shell.getByRole("button", { name: "Aktualisieren", exact: true }).click();
  await shell.locator('[data-worktree-id="tree-web"]').waitFor({ state: "detached" });
  assert.equal(await draft.inputValue(), "Retained nested draft");
  assert.equal(await draft.isVisible(), false);
  assert.equal(await shell.getByRole("region", { name: "Projektgruppe Web", exact: true }).count(), 0);
  await depth.selectOption("3");
  await dashboard.getByRole("button", { name: "Speichern", exact: true }).click();
  await shell.getByRole("button", { name: "Aktualisieren", exact: true }).click();
  await shell.locator('[data-worktree-id="tree-web"]').getByRole("button", { name: "Web api/external/web", exact: true }).click();
  assert.equal(await draft.inputValue(), "Retained nested draft");
  assert.equal(await draft.isVisible(), true);
  assert.deepEqual(errors, []);
  console.log("PASS discovery depth: default, settings persistence, nested project hidden/restored with its draft");
} finally { await browser.close(); }
